    MODULE PARTITION
    IMPLICIT NONE
    REAL(8), PUBLIC ::  M_POLY            ! NUMBER OF POLYMER CHAINS IN THE PERIODICAL CELL
    REAL(8),PUBLIC :: DELTA_W,LAMBDA_W
    REAL(8),PUBLIC::    RG,B2,RHO0 !,KH   !B2-COLIL-COIL VIRIAL COEFFICIENT, RHO0 IS THE INVERSE VOLUME OF THE MONOMER
    REAL(8),PUBLIC:: M2,M2T  !M2 - NUMBER OF CHARGEABLEMONOMERS PER CHAIN
    REAL(8), PUBLIC ::QZ !,QZ0I !SINGLE CHAIN PARTITION FUNCTION
    REAL(8),PUBLIC:: QPLUS,QMINUS,M_PLUS,M_MINUS, M_IONS ! SINGLE ION PARTITION FUNCTIONS AND REFERENCE CONCENTRATIONS: M_IONS=M_PLU+M_MINUS
    REAL(8),PUBLIC ::    MPOLY,MIPLUS, MIMINUS ! INSTANT NUMBER OF POSITIVE AND NEGATIVE SALT IONS IN THE SYSTEM
    REAL(8),PUBLIC ::    ZPOLY,ZPLUS, ZMINUS ! ACTIVITIES OF POLYMERS, AND IONS
    END MODULE PARTITION
