    MODULE BOX
    IMPLICIT NONE
    COMPLEX(8), PARAMETER :: TWOPIIM = (0.,6.2831853071795864769_8)
    REAL(8), PARAMETER :: TWOPI = 6.2831853071795864769_8 , PI2 = 9.8696044010893586188344901_8 
    INTEGER,PUBLIC,PARAMETER :: N_comp=2
    INTEGER,PARAMETER :: NX=128,NY=128,NZ=128
    INTEGER, PUBLIC:: NS 
    INTEGER,PARAMETER :: NT=NX*NY*NZ,NT2=(NX/2+1)*NY*NZ
    REAL(8), PARAMETER :: XI2=1._8/NX**2,YI2=1._8/NY**2,ZI2=1._8/NZ**2, NTI=1./NT
    REAL(8),PUBLIC:: LX,SCALE,LY,LZ,  LXI,  LYI, LZI,LVI, LVN
    REAL(8),PUBLIC:: SCALEx,SCALEy,SCALEz
    
    REAL(8),PUBLIC:: RSCALE !=TWOPI/(LX)
    REAL(8), PUBLIC :: IPHIP(NT)
    PUBLIC :: RDI,RD2,INIT_BOX
    REAL(8), PUBLIC :: D2XI,D2YI,D2ZI    

    CONTAINS 
    SUBROUTINE INIT_BOX()
    SCALE=LX/NX;
    LY=NY*SCALE; LZ=NZ*SCALE ; 
    SCALEX=LX/NX;SCALEY=LY/NY;SCALEZ=LZ/NZ 
    LXI=1./LX ; LYI=1./LY; LZI=1./LZ
    LVI=1/(LX*LY*LZ); LVN=LX*LY*LZ/NT
    !CSCALE=TWOPIIM/(LX)
    RSCALE=TWOPI/(LX)
    D2XI=NX/(2.*LX)
    D2YI=NY/(2.*LY)
    D2ZI=NZ/(2.*LZ)
    END SUBROUTINE INIT_BOX 

    INTEGER FUNCTION RDI(I,NI)
    INTEGER,INTENT(IN)::I,NI
    RDI=MIN(I,NI-I)
    END FUNCTION RDI

    INTEGER FUNCTION RD2(I,NI)
    INTEGER,INTENT(IN)::I,NI
    RD2=MIN(I,NI-I)**2
    END FUNCTION RD2

    REAL(8) ELEMENTAL FUNCTION XLNX(X)
    REAL(8), INTENT(IN) ::X
    IF(X<=0.)THEN
        XLNX=0.
    ELSE
        XLNX=X*LOG(X)
    END IF    
    END FUNCTION XLNX


    END MODULE BOX
    
    